"""empty message

Revision ID: 6d685b622afa
Revises: fb6dc04c4f04
Create Date: 2024-11-02 14:32:33.134476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d685b622afa'
down_revision = 'fb6dc04c4f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('guild_realm_name', sa.String(length=100), nullable=False),
    sa.Column('guild_realm_slug', sa.String(length=100), nullable=False),
    sa.Column('playable_class_id', sa.Integer(), nullable=False),
    sa.Column('playable_race_id', sa.Integer(), nullable=False),
    sa.Column('guild_faction', sa.String(length=50), nullable=False),
    sa.Column('member_realm_slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_member')
    # ### end Alembic commands ###
