"""empty message

Revision ID: c4441a26649c
Revises: 
Create Date: 2024-12-26 18:57:57.109781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4441a26649c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('guild_realm_name', sa.String(length=100), nullable=False),
    sa.Column('guild_realm_slug', sa.String(length=100), nullable=False),
    sa.Column('playable_class_id', sa.Integer(), nullable=False),
    sa.Column('playable_race_id', sa.Integer(), nullable=False),
    sa.Column('guild_faction', sa.String(length=50), nullable=False),
    sa.Column('member_realm_slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('guild_member')
    # ### end Alembic commands ###
